---
- name: start ci runner
  become: true
  command: "{{ ci_runner_dir }}/svc.sh start"

- name: stop ci runner
  become: true
  command: "{{ ci_runner_dir }}/svc.sh stop"

- name: restart ci runner
  become: true
  command: "{{ ci_runner_dir }}/svc.sh restart"
  changed_when: false

- name: uninstall ci runner
  become: true
  command: "{{ ci_runner_dir }}/svc.sh uninstall"
