---
- name: start ci runner
  become: true
  command: ./svc.sh start
  args:
    chdir: "{{ ci_runner_dir }}"

- name: stop ci runner
  become: true
  command: ./svc.sh stop
  args:
    chdir: "{{ ci_runner_dir }}"

- name: restart ci runner
  become: true
  command: ./svc.sh restart
  args:
    chdir: "{{ ci_runner_dir }}"

- name: uninstall ci runner
  become: true
  command: ./svc.sh uninstall
  args:
    chdir: "{{ ci_runner_dir }}"
