servarr_user_shell: /usr/sbin/nologin
servarr_install_root: /opt
servarr_data_root: /var/lib
servarr_upgrade: false

# Required variables (contract)
#
# servarr_name          # sonarr | radarr | lidarr | prowlarr
# servarr_binary        # Sonarr | Radarr | Lidarr | Prowlarr
# servarr_download_url  # official wiki URL
# servarr_port          # 8989 / 7878 / 8686 / 9696
