ci_runner_user: ci-runner
ci_runner_dir: /opt/ci-runner
ci_runner_version: "2.330.0"

ci_runner_repo_url: "https://github.com/JitendraSachwani/homelab-infra"
ci_runner_name: "{{ inventory_hostname }}"
ci_runner_labels:
  - self-hosted
  - homelab
  - linux
  - prod

ci_runner_token_file: "{{ playbook_dir }}/../../keys/ci_runner_token"
