---
- name: IaC Controller | Ensure repo directory exists
  file:
    path: /opt/homelab-infra
    state: directory
    owner: iac
    group: iac
    mode: "0755"

- name: Ensure deploy_prod entrypoint exists
  become: true
  file:
    src: /opt/homelab-infra/90_scripts/deploy_prod.sh
    dest: /usr/local/bin/deploy_prod
    state: link
    force: true
