- name: Install base utilities
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - ca-certificates
      - unzip
      - nfs-common
    state: present

- name: Ensure apt keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Create Tdarr install directory
  ansible.builtin.file:
    path: "{{ tdarr_install_dir }}"
    state: directory
    mode: "0755"

- name: Fetch Tdarr versions metadata
  ansible.builtin.uri:
    url: https://storage.tdarr.io/versions.json
    return_content: true
  register: tdarr_versions

- name: Determine latest Tdarr version
  ansible.builtin.set_fact:
    tdarr_latest_version: >-
      {{
        tdarr_versions.json.keys()
        | list
        | sort
        | last
      }}

- name: Set Tdarr server URL
  ansible.builtin.set_fact:
    tdarr_server_url: >-
      {{
        tdarr_versions.json[tdarr_latest_version].linux_x64.Tdarr_Server
      }}

- name: Check if Tdarr Node is already installed
  ansible.builtin.stat: 
    path: "{{ tdarr_install_dir }}/Tdarr_Server"
  register: tdarr_binary_stat

- name: Download Tdarr server
  ansible.builtin.get_url:
    url: "{{ tdarr_server_url }}"
    dest: "/tmp/tdarr_server.tar.gz"
    mode: "0644"
  when: tdarr_upgrade or not tdarr_binary_stat.stat.exists

- name: Extract Tdarr server
  ansible.builtin.unarchive:
    src: /tmp/tdarr_server.tar.gz
    dest: "{{ tdarr_install_dir }}"
    remote_src: true
  when: tdarr_upgrade or not tdarr_binary_stat.stat.exists

- name: Install Prowlarr
  ansible.builtin.include_role:
    name: servarr_app
  vars:
    servarr_name: prowlarr
    servarr_binary: Prowlarr
    servarr_port: 9696
    servarr_download_url: "http://prowlarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64"
    servarr_dependencies:
      - curl
      - sqlite3

- name: Install Radarr
  ansible.builtin.include_role:
    name: servarr_app
  vars:
    servarr_name: radarr
    servarr_binary: Radarr
    servarr_port: 7878
    servarr_download_url: "http://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64"
    servarr_dependencies:
      - curl
      - sqlite3

- name: Install Sonarr
  ansible.builtin.include_role:
    name: servarr_app
  vars:
    servarr_name: sonarr
    servarr_binary: Sonarr
    servarr_port: 8989
    servarr_download_url: "https://services.sonarr.tv/v1/download/main/latest?version=4&os=linux&arch=x64"
    servarr_dependencies:
      - curl
      - sqlite3

- name: Install Lidarr
  ansible.builtin.include_role:
    name: servarr_app
  vars:
    servarr_name: lidarr
    servarr_binary: Lidarr
    servarr_port: 8686
    servarr_download_url: "http://lidarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64"
    servarr_dependencies:
      - curl
      - sqlite3
      - libchromaprint-tools
      - mediainfo
