name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: prod

jobs:
  validate:
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'push'
    runs-on: [self-hosted, linux, prod]

    steps:
      - uses: actions/checkout@v4

      - name: Terraform init
        working-directory: 10_terraform/envs/prod
        run: terraform init -backend=false

      - name: Terraform fmt
        working-directory: 10_terraform/prod
        run: terraform fmt -check -recursive || (echo "Terraform files need formatting" && exit 1)

      - name: Terraform validate
        working-directory: 10_terraform/envs/prod
        run: terraform validate


  deploy:
    needs: validate
    if: github.event_name == 'push'
    runs-on: [self-hosted, linux, prod]

    concurrency:
      group: homelab-prod-deploy
      cancel-in-progress: false

    steps:
      - name: Trigger prod deploy
        run: |
          ssh -i /home/ci-runner/.ssh/iac_deploy \
              -o StrictHostKeyChecking=no \
              iac@10.0.0.24
